// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ComputeStatus.
const (
	ComputeStatusAllocated ComputeStatus = "allocated"
	ComputeStatusFree      ComputeStatus = "free"
)

// Valid indicates whether the value is a known member of the ComputeStatus enum.
func (e ComputeStatus) Valid() bool {
	switch e {
	case ComputeStatusAllocated:
		return true
	case ComputeStatusFree:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusAborted   JobStatus = "aborted"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
	JobStatusRunning   JobStatus = "running"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusAborted:
		return true
	case JobStatusCompleted:
		return true
	case JobStatusFailed:
		return true
	case JobStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for MirroringActionAction.
const (
	Disable MirroringActionAction = "disable"
	Enable  MirroringActionAction = "enable"
)

// Valid indicates whether the value is a known member of the MirroringActionAction enum.
func (e MirroringActionAction) Valid() bool {
	switch e {
	case Disable:
		return true
	case Enable:
		return true
	default:
		return false
	}
}

// Defines values for PartitionHostsAddMembership.
const (
	PartitionHostsAddMembershipFull    PartitionHostsAddMembership = "full"
	PartitionHostsAddMembershipLimited PartitionHostsAddMembership = "limited"
)

// Valid indicates whether the value is a known member of the PartitionHostsAddMembership enum.
func (e PartitionHostsAddMembership) Valid() bool {
	switch e {
	case PartitionHostsAddMembershipFull:
		return true
	case PartitionHostsAddMembershipLimited:
		return true
	default:
		return false
	}
}

// Defines values for PartitionMemberMembership.
const (
	PartitionMemberMembershipFull    PartitionMemberMembership = "full"
	PartitionMemberMembershipLimited PartitionMemberMembership = "limited"
)

// Valid indicates whether the value is a known member of the PartitionMemberMembership enum.
func (e PartitionMemberMembership) Valid() bool {
	switch e {
	case PartitionMemberMembershipFull:
		return true
	case PartitionMemberMembershipLimited:
		return true
	default:
		return false
	}
}

// Defines values for PartitionMemberInputMembership.
const (
	Full    PartitionMemberInputMembership = "full"
	Limited PartitionMemberInputMembership = "limited"
)

// Valid indicates whether the value is a known member of the PartitionMemberInputMembership enum.
func (e PartitionMemberInputMembership) Valid() bool {
	switch e {
	case Full:
		return true
	case Limited:
		return true
	default:
		return false
	}
}

// Defines values for PartitionQoSMtuLimit.
const (
	N2 PartitionQoSMtuLimit = 2
	N4 PartitionQoSMtuLimit = 4
)

// Valid indicates whether the value is a known member of the PartitionQoSMtuLimit enum.
func (e PartitionQoSMtuLimit) Valid() bool {
	switch e {
	case N2:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// Defines values for ReportCreateType.
const (
	FabricHealth    ReportCreateType = "Fabric_Health"
	TopologyCompare ReportCreateType = "Topology_Compare"
	UFMHealth       ReportCreateType = "UFM_Health"
)

// Valid indicates whether the value is a known member of the ReportCreateType enum.
func (e ReportCreateType) Valid() bool {
	switch e {
	case FabricHealth:
		return true
	case TopologyCompare:
		return true
	case UFMHealth:
		return true
	default:
		return false
	}
}

// Defines values for SystemRole.
const (
	SystemRoleCore     SystemRole = "core"
	SystemRoleEndpoint SystemRole = "endpoint"
	SystemRoleTor      SystemRole = "tor"
)

// Valid indicates whether the value is a known member of the SystemRole enum.
func (e SystemRole) Valid() bool {
	switch e {
	case SystemRoleCore:
		return true
	case SystemRoleEndpoint:
		return true
	case SystemRoleTor:
		return true
	default:
		return false
	}
}

// Defines values for SystemType.
const (
	SystemTypeGateway SystemType = "gateway"
	SystemTypeHost    SystemType = "host"
	SystemTypeRouter  SystemType = "router"
	SystemTypeSwitch  SystemType = "switch"
)

// Valid indicates whether the value is a known member of the SystemType enum.
func (e SystemType) Valid() bool {
	switch e {
	case SystemTypeGateway:
		return true
	case SystemTypeHost:
		return true
	case SystemTypeRouter:
		return true
	case SystemTypeSwitch:
		return true
	default:
		return false
	}
}

// Defines values for AssignComputesJSONBodyMode.
const (
	Auto   AssignComputesJSONBodyMode = "auto"
	Manual AssignComputesJSONBodyMode = "manual"
)

// Valid indicates whether the value is a known member of the AssignComputesJSONBodyMode enum.
func (e AssignComputesJSONBodyMode) Valid() bool {
	switch e {
	case Auto:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsStatus.
const (
	ListJobsParamsStatusAborted   ListJobsParamsStatus = "aborted"
	ListJobsParamsStatusCompleted ListJobsParamsStatus = "completed"
	ListJobsParamsStatusFailed    ListJobsParamsStatus = "failed"
	ListJobsParamsStatusRunning   ListJobsParamsStatus = "running"
)

// Valid indicates whether the value is a known member of the ListJobsParamsStatus enum.
func (e ListJobsParamsStatus) Valid() bool {
	switch e {
	case ListJobsParamsStatusAborted:
		return true
	case ListJobsParamsStatusCompleted:
		return true
	case ListJobsParamsStatusFailed:
		return true
	case ListJobsParamsStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ListPortsParamsHighBerSeverity.
const (
	ListPortsParamsHighBerSeverityError   ListPortsParamsHighBerSeverity = "error"
	ListPortsParamsHighBerSeverityWarning ListPortsParamsHighBerSeverity = "warning"
)

// Valid indicates whether the value is a known member of the ListPortsParamsHighBerSeverity enum.
func (e ListPortsParamsHighBerSeverity) Valid() bool {
	switch e {
	case ListPortsParamsHighBerSeverityError:
		return true
	case ListPortsParamsHighBerSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for ListSystemsParamsType.
const (
	ListSystemsParamsTypeGateway ListSystemsParamsType = "gateway"
	ListSystemsParamsTypeHost    ListSystemsParamsType = "host"
	ListSystemsParamsTypeRouter  ListSystemsParamsType = "router"
	ListSystemsParamsTypeSwitch  ListSystemsParamsType = "switch"
)

// Valid indicates whether the value is a known member of the ListSystemsParamsType enum.
func (e ListSystemsParamsType) Valid() bool {
	switch e {
	case ListSystemsParamsTypeGateway:
		return true
	case ListSystemsParamsTypeHost:
		return true
	case ListSystemsParamsTypeRouter:
		return true
	case ListSystemsParamsTypeSwitch:
		return true
	default:
		return false
	}
}

// Defines values for ListSystemsParamsRole.
const (
	ListSystemsParamsRoleCore     ListSystemsParamsRole = "core"
	ListSystemsParamsRoleEndpoint ListSystemsParamsRole = "endpoint"
	ListSystemsParamsRoleTor      ListSystemsParamsRole = "tor"
)

// Valid indicates whether the value is a known member of the ListSystemsParamsRole enum.
func (e ListSystemsParamsRole) Valid() bool {
	switch e {
	case ListSystemsParamsRoleCore:
		return true
	case ListSystemsParamsRoleEndpoint:
		return true
	case ListSystemsParamsRoleTor:
		return true
	default:
		return false
	}
}

// Defines values for ListSystemsParamsComputeStatus.
const (
	ListSystemsParamsComputeStatusAllocated ListSystemsParamsComputeStatus = "allocated"
	ListSystemsParamsComputeStatusFree      ListSystemsParamsComputeStatus = "free"
)

// Valid indicates whether the value is a known member of the ListSystemsParamsComputeStatus enum.
func (e ListSystemsParamsComputeStatus) Valid() bool {
	switch e {
	case ListSystemsParamsComputeStatusAllocated:
		return true
	case ListSystemsParamsComputeStatusFree:
		return true
	default:
		return false
	}
}

// Compute defines model for Compute.
type Compute struct {
	Name   *string        `json:"name,omitempty"`
	Status *ComputeStatus `json:"status,omitempty"`
}

// ComputeStatus defines model for Compute.Status.
type ComputeStatus string

// Environment defines model for Environment.
type Environment struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// EnvironmentCreate defines model for EnvironmentCreate.
type EnvironmentCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// EnvironmentList defines model for EnvironmentList.
type EnvironmentList struct {
	Items    *[]Environment `json:"items,omitempty"`
	PageInfo *PageInfo      `json:"page_info,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Machine-readable error code.
		Code    string `json:"code"`
		Details *[]struct {
			Field  *string `json:"field,omitempty"`
			Reason *string `json:"reason,omitempty"`
		} `json:"details,omitempty"`

		// Message Human-readable error description.
		Message string `json:"message"`
	} `json:"error"`
}

// Job defines model for Job.
type Job struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Operation   *string    `json:"operation,omitempty"`
	Status      *JobStatus `json:"status,omitempty"`

	// SubJobs Present only when `include=sub_jobs`.
	SubJobs *[]Job `json:"sub_jobs,omitempty"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobList defines model for JobList.
type JobList struct {
	Items    *[]Job    `json:"items,omitempty"`
	PageInfo *PageInfo `json:"page_info,omitempty"`
}

// Link defines model for Link.
type Link struct {
	DestinationPort *string `json:"destination_port,omitempty"`
	SourcePort      *string `json:"source_port,omitempty"`
	Speed           *string `json:"speed,omitempty"`
	Width           *string `json:"width,omitempty"`
}

// LinkList defines model for LinkList.
type LinkList struct {
	Items    *[]Link   `json:"items,omitempty"`
	PageInfo *PageInfo `json:"page_info,omitempty"`
}

// LogicalServer defines model for LogicalServer.
type LogicalServer struct {
	Computes    *[]Compute `json:"computes,omitempty"`
	Description *string    `json:"description,omitempty"`
	Name        *string    `json:"name,omitempty"`
}

// LogicalServerCreate defines model for LogicalServerCreate.
type LogicalServerCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// MirroringAction defines model for MirroringAction.
type MirroringAction struct {
	Action MirroringActionAction `json:"action"`
	PortId string                `json:"port_id"`
	Rx     *bool                 `json:"rx,omitempty"`
	Tx     *bool                 `json:"tx,omitempty"`
}

// MirroringActionAction defines model for MirroringAction.Action.
type MirroringActionAction string

// MirroringTemplate defines model for MirroringTemplate.
type MirroringTemplate struct {
	PacketSize   *int    `json:"packet_size,omitempty"`
	ServiceLevel *int    `json:"service_level,omitempty"`
	SystemId     *string `json:"system_id,omitempty"`
	TargetPort   *string `json:"target_port,omitempty"`
}

// MonitoringSession defines model for MonitoringSession.
type MonitoringSession struct {
	Attributes *[]string `json:"attributes,omitempty"`
	Id         *string   `json:"id,omitempty"`
	Interval   *int      `json:"interval,omitempty"`
	Status     *string   `json:"status,omitempty"`
}

// MonitoringSessionCreate defines model for MonitoringSessionCreate.
type MonitoringSessionCreate struct {
	Attributes *[]string `json:"attributes,omitempty"`

	// Interval Collection interval in seconds.
	Interval *int      `json:"interval,omitempty"`
	Members  *[]string `json:"members,omitempty"`
}

// MonitoringSnapshotCreate defines model for MonitoringSnapshotCreate.
type MonitoringSnapshotCreate struct {
	Attributes *[]string `json:"attributes,omitempty"`
	Members    *[]string `json:"members,omitempty"`
}

// MonitoringTemplate defines model for MonitoringTemplate.
type MonitoringTemplate struct {
	Attributes *[]string `json:"attributes,omitempty"`
	Interval   *int      `json:"interval,omitempty"`
	Name       *string   `json:"name,omitempty"`
}

// Network defines model for Network.
type Network struct {
	IpOverIb *bool   `json:"ip_over_ib,omitempty"`
	Name     *string `json:"name,omitempty"`
	Pkey     *string `json:"pkey,omitempty"`
}

// NetworkCreate defines model for NetworkCreate.
type NetworkCreate struct {
	IpOverIb *bool   `json:"ip_over_ib,omitempty"`
	Name     string  `json:"name"`
	Pkey     *string `json:"pkey,omitempty"`
}

// PageInfo defines model for PageInfo.
type PageInfo struct {
	// NextCursor Cursor for next page, null if last page.
	NextCursor *string `json:"next_cursor,omitempty"`

	// Total Total number of items (if known).
	Total *int `json:"total,omitempty"`
}

// Partition defines model for Partition.
type Partition struct {
	Index0   *bool `json:"index0,omitempty"`
	IpOverIb *bool `json:"ip_over_ib,omitempty"`

	// Members Present only when `include=members`.
	Members *[]PartitionMember `json:"members,omitempty"`
	Name    *string            `json:"name,omitempty"`

	// Pkey Partition key in hex (e.g. `0x8001`).
	Pkey         *string       `json:"pkey,omitempty"`
	Qos          *PartitionQoS `json:"qos,omitempty"`
	SharpEnabled *bool         `json:"sharp_enabled,omitempty"`
}

// PartitionCreate defines model for PartitionCreate.
type PartitionCreate struct {
	Index0   *bool `json:"index0,omitempty"`
	IpOverIb *bool `json:"ip_over_ib,omitempty"`

	// Members Optional initial GUID members. If omitted, an empty
	// partition is created.
	Members *[]PartitionMemberInput `json:"members,omitempty"`
	Name    *string                 `json:"name,omitempty"`
	Pkey    string                  `json:"pkey"`
	Qos     *PartitionQoS           `json:"qos,omitempty"`
}

// PartitionHostsAdd defines model for PartitionHostsAdd.
type PartitionHostsAdd struct {
	// Hosts Hostnames to add.
	Hosts      []string                     `json:"hosts"`
	Index0     *bool                        `json:"index0,omitempty"`
	IpOverIb   *bool                        `json:"ip_over_ib,omitempty"`
	Membership *PartitionHostsAddMembership `json:"membership,omitempty"`
}

// PartitionHostsAddMembership defines model for PartitionHostsAdd.Membership.
type PartitionHostsAddMembership string

// PartitionList defines model for PartitionList.
type PartitionList struct {
	Items    *[]Partition `json:"items,omitempty"`
	PageInfo *PageInfo    `json:"page_info,omitempty"`
}

// PartitionMember defines model for PartitionMember.
type PartitionMember struct {
	Guid       *string                    `json:"guid,omitempty"`
	Index0     *bool                      `json:"index0,omitempty"`
	Membership *PartitionMemberMembership `json:"membership,omitempty"`
}

// PartitionMemberMembership defines model for PartitionMember.Membership.
type PartitionMemberMembership string

// PartitionMemberInput defines model for PartitionMemberInput.
type PartitionMemberInput struct {
	Guid       string                          `json:"guid"`
	Membership *PartitionMemberInputMembership `json:"membership,omitempty"`
}

// PartitionMemberInputMembership defines model for PartitionMemberInput.Membership.
type PartitionMemberInputMembership string

// PartitionMemberList defines model for PartitionMemberList.
type PartitionMemberList struct {
	Items    *[]PartitionMember `json:"items,omitempty"`
	PageInfo *PageInfo          `json:"page_info,omitempty"`
}

// PartitionMembersAdd defines model for PartitionMembersAdd.
type PartitionMembersAdd struct {
	Index0   *bool                  `json:"index0,omitempty"`
	IpOverIb *bool                  `json:"ip_over_ib,omitempty"`
	Members  []PartitionMemberInput `json:"members"`
}

// PartitionQoS defines model for PartitionQoS.
type PartitionQoS struct {
	// MtuLimit MTU limit: 2 = 2048, 4 = 4096.
	MtuLimit *PartitionQoSMtuLimit `json:"mtu_limit,omitempty"`

	// RateLimit Rate limit (predefined values).
	RateLimit    *float32 `json:"rate_limit,omitempty"`
	ServiceLevel *int     `json:"service_level,omitempty"`
}

// PartitionQoSMtuLimit MTU limit: 2 = 2048, 4 = 4096.
type PartitionQoSMtuLimit int

// PartitionReplace defines model for PartitionReplace.
type PartitionReplace struct {
	Index0   *bool                  `json:"index0,omitempty"`
	IpOverIb *bool                  `json:"ip_over_ib,omitempty"`
	Members  []PartitionMemberInput `json:"members"`
	Name     *string                `json:"name,omitempty"`
	Qos      *PartitionQoS          `json:"qos,omitempty"`
}

// Port defines model for Port.
type Port struct {
	// CableInfo Present only when `include=cable_info`.
	CableInfo          *map[string]interface{} `json:"cable_info,omitempty"`
	External           *bool                   `json:"external,omitempty"`
	Guid               *string                 `json:"guid,omitempty"`
	LogicalPortState   *string                 `json:"logical_port_state,omitempty"`
	Name               *string                 `json:"name,omitempty"`
	PhysicalPortNumber *int                    `json:"physical_port_number,omitempty"`
	PhysicalPortState  *string                 `json:"physical_port_state,omitempty"`
	Speed              *string                 `json:"speed,omitempty"`
	SystemGuid         *string                 `json:"system_guid,omitempty"`
	SystemName         *string                 `json:"system_name,omitempty"`
	Width              *string                 `json:"width,omitempty"`
}

// PortList defines model for PortList.
type PortList struct {
	Items    *[]Port   `json:"items,omitempty"`
	PageInfo *PageInfo `json:"page_info,omitempty"`
}

// ProvisioningTemplate defines model for ProvisioningTemplate.
type ProvisioningTemplate struct {
	// Content Template command sequence.
	Content     *[]map[string]interface{} `json:"content,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Owner       *string                   `json:"owner,omitempty"`
	SystemType  *string                   `json:"system_type,omitempty"`
	Tags        *[]string                 `json:"tags,omitempty"`
	Title       *string                   `json:"title,omitempty"`
}

// ProvisioningTemplateCreate defines model for ProvisioningTemplateCreate.
type ProvisioningTemplateCreate struct {
	Content     []map[string]interface{} `json:"content"`
	Description *string                  `json:"description,omitempty"`
	SystemType  string                   `json:"system_type"`
	Title       string                   `json:"title"`
}

// ReportCreate defines model for ReportCreate.
type ReportCreate struct {
	// Parameters Report-specific configuration parameters.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Type       ReportCreateType        `json:"type"`
}

// ReportCreateType defines model for ReportCreate.Type.
type ReportCreateType string

// System defines model for System.
type System struct {
	Description     *string `json:"description,omitempty"`
	FirmwareVersion *string `json:"firmware_version,omitempty"`
	Guid            *string `json:"guid,omitempty"`
	Ip              *string `json:"ip,omitempty"`
	Model           *string `json:"model,omitempty"`
	Name            *string `json:"name,omitempty"`

	// Ports Present only when `include=ports`.
	Ports  *[]Port     `json:"ports,omitempty"`
	Role   *SystemRole `json:"role,omitempty"`
	Type   *SystemType `json:"type,omitempty"`
	Vendor *string     `json:"vendor,omitempty"`
}

// SystemRole defines model for System.Role.
type SystemRole string

// SystemType defines model for System.Type.
type SystemType string

// SystemList defines model for SystemList.
type SystemList struct {
	Items    *[]System `json:"items,omitempty"`
	PageInfo *PageInfo `json:"page_info,omitempty"`
}

// SystemPower defines model for SystemPower.
type SystemPower struct {
	PowerWatts *float32 `json:"power_watts,omitempty"`
	SystemId   *string  `json:"system_id,omitempty"`
}

// SystemUpdate defines model for SystemUpdate.
type SystemUpdate struct {
	Ip     *string `json:"ip,omitempty"`
	Name   *string `json:"name,omitempty"`
	Script *string `json:"script,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// UFMConfig defines model for UFMConfig.
type UFMConfig struct {
	DefaultSessionInterval *int      `json:"default_session_interval,omitempty"`
	DisabledFeatures       *[]string `json:"disabled_features,omitempty"`
	HaMode                 *string   `json:"ha_mode,omitempty"`
	IsLocalUser            *bool     `json:"is_local_user,omitempty"`
	SiteName               *string   `json:"site_name,omitempty"`
}

// UFMVersion defines model for UFMVersion.
type UFMVersion struct {
	IbdiagnetVersion  *string            `json:"ibdiagnet_version,omitempty"`
	MftVersion        *string            `json:"mft_version,omitempty"`
	OpensmVersion     *string            `json:"opensm_version,omitempty"`
	Plugins           *map[string]string `json:"plugins,omitempty"`
	SharpVersion      *string            `json:"sharp_version,omitempty"`
	TelemetryVersion  *string            `json:"telemetry_version,omitempty"`
	UfmReleaseVersion *string            `json:"ufm_release_version,omitempty"`
	WebuiVersion      *string            `json:"webui_version,omitempty"`
}

// VirtualPort defines model for VirtualPort.
type VirtualPort struct {
	PhysicalPortNumber *int    `json:"physical_port_number,omitempty"`
	PortGuid           *string `json:"port_guid,omitempty"`
	PortName           *string `json:"port_name,omitempty"`
	SystemGuid         *string `json:"system_guid,omitempty"`
	SystemIp           *string `json:"system_ip,omitempty"`
	SystemName         *string `json:"system_name,omitempty"`
	VirtualPortGuid    *string `json:"virtual_port_guid,omitempty"`
	VirtualPortLid     *int    `json:"virtual_port_lid,omitempty"`
	VirtualPortState   *string `json:"virtual_port_state,omitempty"`
}

// VirtualPortList defines model for VirtualPortList.
type VirtualPortList struct {
	Items    *[]VirtualPort `json:"items,omitempty"`
	PageInfo *PageInfo      `json:"page_info,omitempty"`
}

// Cursor defines model for cursor.
type Cursor = string

// Limit defines model for limit.
type Limit = int

// Pkey defines model for pkey.
type Pkey = string

// NotFound defines model for NotFound.
type NotFound = Error

// UploadCableImageMultipartBody defines parameters for UploadCableImage.
type UploadCableImageMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// UpdateConfigJSONBody defines parameters for UpdateConfig.
type UpdateConfigJSONBody map[string]interface{}

// ConfigureDumpStorageJSONBody defines parameters for ConfigureDumpStorage.
type ConfigureDumpStorageJSONBody struct {
	StoragePath *string `json:"storage_path,omitempty"`
}

// GetInventorySummaryParams defines parameters for GetInventorySummary.
type GetInventorySummaryParams struct {
	IncludePorts *bool `form:"include_ports,omitempty" json:"include_ports,omitempty"`
}

// ListEnvironmentsParams defines parameters for ListEnvironments.
type ListEnvironmentsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// AssignComputesJSONBody defines parameters for AssignComputes.
type AssignComputesJSONBody struct {
	// Computes Compute names (required for manual mode).
	Computes *[]string                   `json:"computes,omitempty"`
	Mode     *AssignComputesJSONBodyMode `json:"mode,omitempty"`
}

// AssignComputesJSONBodyMode defines parameters for AssignComputes.
type AssignComputesJSONBodyMode string

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Status Filter by job status.
	Status *ListJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Operation Filter by operation type.
	Operation *string `form:"operation,omitempty" json:"operation,omitempty"`

	// ParentOnly Only return parent jobs (exclude sub-jobs).
	ParentOnly *bool `form:"parent_only,omitempty" json:"parent_only,omitempty"`

	// SystemIds Filter by associated system IDs (comma-separated).
	SystemIds *string `form:"system_ids,omitempty" json:"system_ids,omitempty"`
}

// ListJobsParamsStatus defines parameters for ListJobs.
type ListJobsParamsStatus string

// GetJobParams defines parameters for GetJob.
type GetJobParams struct {
	// Include Additional data: `sub_jobs`, `full`.
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// ListLinksParams defines parameters for ListLinks.
type ListLinksParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CollectLinkDumpJSONBody defines parameters for CollectLinkDump.
type CollectLinkDumpJSONBody struct {
	LinkIds []string `json:"link_ids"`
}

// GetPerformanceCountersJSONBody defines parameters for GetPerformanceCounters.
type GetPerformanceCountersJSONBody struct {
	Hostnames []string `json:"hostnames"`
}

// GetMonitoringSessionDataParams defines parameters for GetMonitoringSessionData.
type GetMonitoringSessionDataParams struct {
	// Partition Filter by PKEY.
	Partition *string `form:"partition,omitempty" json:"partition,omitempty"`
}

// ListPartitionsParams defines parameters for ListPartitions.
type ListPartitionsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Include Comma-separated list of additional data to include.
	// Supported values: `members`, `qos`, `port_info`, `sharp_state`.
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// GetPartitionParams defines parameters for GetPartition.
type GetPartitionParams struct {
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// RemovePartitionHostsJSONBody defines parameters for RemovePartitionHosts.
type RemovePartitionHostsJSONBody struct {
	// Hosts Hostnames to remove.
	Hosts []string `json:"hosts"`
}

// RemovePartitionMembersJSONBody defines parameters for RemovePartitionMembers.
type RemovePartitionMembersJSONBody struct {
	// Guids GUIDs to remove.
	Guids []string `json:"guids"`
}

// ListPartitionMembersParams defines parameters for ListPartitionMembers.
type ListPartitionMembersParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdatePartitionSHARPJSONBody defines parameters for UpdatePartitionSHARP.
type UpdatePartitionSHARPJSONBody struct {
	// Enabled Enable or disable SHARP reservation for this partition.
	Enabled bool `json:"enabled"`
}

// ListPortsParams defines parameters for ListPorts.
type ListPortsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// System Filter by system name.
	System *string `form:"system,omitempty" json:"system,omitempty"`

	// SystemType Filter by system type (e.g. Switch).
	SystemType *string `form:"system_type,omitempty" json:"system_type,omitempty"`

	// Active Only return active ports.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// External Only return external ports.
	External *bool `form:"external,omitempty" json:"external,omitempty"`

	// HighBer Only return high BER ports.
	HighBer *bool `form:"high_ber,omitempty" json:"high_ber,omitempty"`

	// HighBerSeverity Filter high BER ports by severity.
	HighBerSeverity *ListPortsParamsHighBerSeverity `form:"high_ber_severity,omitempty" json:"high_ber_severity,omitempty"`

	// Include Additional data: `cable_info`.
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// ListPortsParamsHighBerSeverity defines parameters for ListPorts.
type ListPortsParamsHighBerSeverity string

// ListSystemsParams defines parameters for ListSystems.
type ListSystemsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Type Filter by system type.
	Type *ListSystemsParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Model Filter by switch model.
	Model *string `form:"model,omitempty" json:"model,omitempty"`

	// Role Filter by topology role.
	Role *ListSystemsParamsRole `form:"role,omitempty" json:"role,omitempty"`

	// Ip Filter by system IP address.
	Ip *string `form:"ip,omitempty" json:"ip,omitempty"`

	// Rack Filter by rack membership.
	Rack *string `form:"rack,omitempty" json:"rack,omitempty"`

	// ComputeStatus Filter by compute allocation status.
	ComputeStatus *ListSystemsParamsComputeStatus `form:"compute_status,omitempty" json:"compute_status,omitempty"`

	// Include Comma-separated additional data: `ports`, `chassis`, `brief`.
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// ListSystemsParamsType defines parameters for ListSystems.
type ListSystemsParamsType string

// ListSystemsParamsRole defines parameters for ListSystems.
type ListSystemsParamsRole string

// ListSystemsParamsComputeStatus defines parameters for ListSystems.
type ListSystemsParamsComputeStatus string

// GetSystemParams defines parameters for GetSystem.
type GetSystemParams struct {
	Include *string `form:"include,omitempty" json:"include,omitempty"`
}

// UpgradeSystemFirmwareJSONBody defines parameters for UpgradeSystemFirmware.
type UpgradeSystemFirmwareJSONBody struct {
	// Image Firmware image name.
	Image  *string `json:"image,omitempty"`
	InBand *bool   `json:"in_band,omitempty"`
}

// SetSystemHealthJSONBody defines parameters for SetSystemHealth.
type SetSystemHealthJSONBody struct {
	Healthy bool `json:"healthy"`

	// IsolationPolicy Isolation policy when marking unhealthy.
	IsolationPolicy *string `json:"isolation_policy,omitempty"`
}

// RebootSystemJSONBody defines parameters for RebootSystem.
type RebootSystemJSONBody struct {
	// InBand Use in-band reboot for unmanaged switches.
	InBand *bool `json:"in_band,omitempty"`
}

// UpgradeSystemSoftwareJSONBody defines parameters for UpgradeSystemSoftware.
type UpgradeSystemSoftwareJSONBody struct {
	// Image Software image name.
	Image *string `json:"image,omitempty"`
}

// GetHistoryTelemetryParams defines parameters for GetHistoryTelemetry.
type GetHistoryTelemetryParams struct {
	MembersType string `form:"members_type" json:"members_type"`
	Attributes  string `form:"attributes" json:"attributes"`

	// Members Comma-separated list of member GUIDs.
	Members string `form:"members" json:"members"`

	// StartTime Relative or absolute start time (e.g. `-1h`).
	StartTime string `form:"start_time" json:"start_time"`

	// EndTime Relative or absolute end time (e.g. `-0min`).
	EndTime string `form:"end_time" json:"end_time"`
}

// GetTopTelemetryParams defines parameters for GetTopTelemetry.
type GetTopTelemetryParams struct {
	MembersType string `form:"members_type" json:"members_type"`
	PickBy      string `form:"pick_by" json:"pick_by"`
	Limit       *int   `form:"limit,omitempty" json:"limit,omitempty"`

	// Attributes Additional telemetry attributes to include.
	Attributes *string `form:"attributes,omitempty" json:"attributes,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Tags       *string `form:"tags,omitempty" json:"tags,omitempty"`
	Profile    *string `form:"profile,omitempty" json:"profile,omitempty"`
	SystemType *string `form:"system_type,omitempty" json:"system_type,omitempty"`
}

// ExecuteTemplateJSONBody defines parameters for ExecuteTemplate.
type ExecuteTemplateJSONBody struct {
	SystemIds []string `json:"system_ids"`
}

// ListVirtualPortsParams defines parameters for ListVirtualPorts.
type ListVirtualPortsParams struct {
	// Cursor Pagination cursor from a previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (default 100, max 1000).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// System Filter by system GUID.
	System *string `form:"system,omitempty" json:"system,omitempty"`

	// Port Filter by physical port name.
	Port *string `form:"port,omitempty" json:"port,omitempty"`
}

// UploadCableImageMultipartRequestBody defines body for UploadCableImage for multipart/form-data ContentType.
type UploadCableImageMultipartRequestBody UploadCableImageMultipartBody

// UpdateConfigJSONRequestBody defines body for UpdateConfig for application/json ContentType.
type UpdateConfigJSONRequestBody UpdateConfigJSONBody

// ConfigureDumpStorageJSONRequestBody defines body for ConfigureDumpStorage for application/json ContentType.
type ConfigureDumpStorageJSONRequestBody ConfigureDumpStorageJSONBody

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = EnvironmentCreate

// UpdateEnvironmentJSONRequestBody defines body for UpdateEnvironment for application/json ContentType.
type UpdateEnvironmentJSONRequestBody = EnvironmentCreate

// CreateLocalNetworkJSONRequestBody defines body for CreateLocalNetwork for application/json ContentType.
type CreateLocalNetworkJSONRequestBody = NetworkCreate

// CreateLogicalServerJSONRequestBody defines body for CreateLogicalServer for application/json ContentType.
type CreateLogicalServerJSONRequestBody = LogicalServerCreate

// AssignComputesJSONRequestBody defines body for AssignComputes for application/json ContentType.
type AssignComputesJSONRequestBody AssignComputesJSONBody

// CollectLinkDumpJSONRequestBody defines body for CollectLinkDump for application/json ContentType.
type CollectLinkDumpJSONRequestBody CollectLinkDumpJSONBody

// CreateMirroringTemplateJSONRequestBody defines body for CreateMirroringTemplate for application/json ContentType.
type CreateMirroringTemplateJSONRequestBody = MirroringTemplate

// ExecuteMirroringActionJSONRequestBody defines body for ExecuteMirroringAction for application/json ContentType.
type ExecuteMirroringActionJSONRequestBody = MirroringAction

// UpdateMirroringTemplateJSONRequestBody defines body for UpdateMirroringTemplate for application/json ContentType.
type UpdateMirroringTemplateJSONRequestBody = MirroringTemplate

// GetPerformanceCountersJSONRequestBody defines body for GetPerformanceCounters for application/json ContentType.
type GetPerformanceCountersJSONRequestBody GetPerformanceCountersJSONBody

// CreateMonitoringSessionJSONRequestBody defines body for CreateMonitoringSession for application/json ContentType.
type CreateMonitoringSessionJSONRequestBody = MonitoringSessionCreate

// CreateMonitoringSnapshotJSONRequestBody defines body for CreateMonitoringSnapshot for application/json ContentType.
type CreateMonitoringSnapshotJSONRequestBody = MonitoringSnapshotCreate

// CreateMonitoringTemplateJSONRequestBody defines body for CreateMonitoringTemplate for application/json ContentType.
type CreateMonitoringTemplateJSONRequestBody = MonitoringTemplate

// UpdateMonitoringTemplateJSONRequestBody defines body for UpdateMonitoringTemplate for application/json ContentType.
type UpdateMonitoringTemplateJSONRequestBody = MonitoringTemplate

// CreateGlobalNetworkJSONRequestBody defines body for CreateGlobalNetwork for application/json ContentType.
type CreateGlobalNetworkJSONRequestBody = NetworkCreate

// UpdateGlobalNetworkJSONRequestBody defines body for UpdateGlobalNetwork for application/json ContentType.
type UpdateGlobalNetworkJSONRequestBody = NetworkCreate

// CreatePartitionJSONRequestBody defines body for CreatePartition for application/json ContentType.
type CreatePartitionJSONRequestBody = PartitionCreate

// ReplacePartitionJSONRequestBody defines body for ReplacePartition for application/json ContentType.
type ReplacePartitionJSONRequestBody = PartitionReplace

// RemovePartitionHostsJSONRequestBody defines body for RemovePartitionHosts for application/json ContentType.
type RemovePartitionHostsJSONRequestBody RemovePartitionHostsJSONBody

// AddPartitionHostsJSONRequestBody defines body for AddPartitionHosts for application/json ContentType.
type AddPartitionHostsJSONRequestBody = PartitionHostsAdd

// RemovePartitionMembersJSONRequestBody defines body for RemovePartitionMembers for application/json ContentType.
type RemovePartitionMembersJSONRequestBody RemovePartitionMembersJSONBody

// AddPartitionMembersJSONRequestBody defines body for AddPartitionMembers for application/json ContentType.
type AddPartitionMembersJSONRequestBody = PartitionMembersAdd

// UpdatePartitionQoSJSONRequestBody defines body for UpdatePartitionQoS for application/json ContentType.
type UpdatePartitionQoSJSONRequestBody = PartitionQoS

// UpdatePartitionSHARPJSONRequestBody defines body for UpdatePartitionSHARP for application/json ContentType.
type UpdatePartitionSHARPJSONRequestBody UpdatePartitionSHARPJSONBody

// CreateReportJSONRequestBody defines body for CreateReport for application/json ContentType.
type CreateReportJSONRequestBody = ReportCreate

// UpdateSystemJSONRequestBody defines body for UpdateSystem for application/json ContentType.
type UpdateSystemJSONRequestBody = SystemUpdate

// UpgradeSystemFirmwareJSONRequestBody defines body for UpgradeSystemFirmware for application/json ContentType.
type UpgradeSystemFirmwareJSONRequestBody UpgradeSystemFirmwareJSONBody

// SetSystemHealthJSONRequestBody defines body for SetSystemHealth for application/json ContentType.
type SetSystemHealthJSONRequestBody SetSystemHealthJSONBody

// RebootSystemJSONRequestBody defines body for RebootSystem for application/json ContentType.
type RebootSystemJSONRequestBody RebootSystemJSONBody

// UpgradeSystemSoftwareJSONRequestBody defines body for UpgradeSystemSoftware for application/json ContentType.
type UpgradeSystemSoftwareJSONRequestBody UpgradeSystemSoftwareJSONBody

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = ProvisioningTemplateCreate

// ExecuteTemplateJSONRequestBody defines body for ExecuteTemplate for application/json ContentType.
type ExecuteTemplateJSONRequestBody ExecuteTemplateJSONBody
